# Crear file general
diagCovid.exe: diagCovid.o funciones.o
	gcc diagCovid.o funciones.o -o diagCovid.exe

#Crear objeto main
diagCovid.o: diagCovid.c
	gcc -c diagCovid.c

#Crear objeto funciones
funciones.o: funciones.c
	gcc -c funciones.c
