vacuna.exe: vacuna.o funciones.o funcion1.o funcion2.o
	gcc vacuna.o funciones.o funcion1.o funcion2.o -o vacuna.exe

vacuna.o: vacuna.c
	gcc -c vacuna.c

funciones.o: funciones.c
	gcc -c funciones.c

funcion1.o: funcion1.c
	gcc -c funcion1.c

funcion2.o: funcion2.c
	gcc -c funcion2.c
